import bcrypt from 'bcrypt';

// const data = {
//   users: [
//     {
//       name: 'John',
//       email: 'admin@example.com',
//       password: bcrypt.hashSync('123456', 10),
//       isAdmin: true,
//     },
//     {
//       name: 'Jane',
//       email: 'user@example.com',
//       password: bcrypt.hashSync('123456', 10),
//       isAdmin: false,
//     },
//   ],
//   products: [
//     {
//       name: "Free Shirt",
//       category: "Shirts",
//       slug: 'free-shirt',
//       image: "/images/tyres.jpeg",
//       price: 70,
//       brand: "Nike",
//       rating: 4.5,
//       numReviews: 10,
//       countInStock: 20,
//       description: "A popular shirt Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
//     },
//     {
//       name: "Fit Shirt",
//       category: "Shirts",
//       slug: 'fit-shirt',
//       image: "/images/tyres.jpeg",
//       price: 80,
//       brand: "Adidas",
//       rating: 4.2,
//       numReviews: 10,
//       countInStock: 20,
//       description: "A popular shirt Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
//     },
//     {
//       name: "Slim Shirt",
//       category: "Shirts",
//       slug: 'slim-shirt',
//       image: "/images/tyres.jpeg",
//       price: 90,
//       brand: "Raymond",
//       rating: 4.5,
//       numReviews: 10,
//       countInStock: 20,
//       description: "A popular shirt Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
//     },
//     {
//       name: "Golf Pants",
//       category: "Pants",
//       slug: 'golf-pants',
//       image: "/images/tyres.jpeg",
//       price: 90,
//       brand: "Oliver",
//       rating: 4.5,
//       numReviews: 10,
//       countInStock: 20,
//       description: "Smart looking pants Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
//     },
//     {
//       name: "Fit Pants",
//       category: "Pants",
//       slug: 'fit-pants',
//       image: "/images/tyres.jpeg",
//       price: 95,
//       brand: "Zara",
//       rating: 4.5,
//       numReviews: 10,
//       countInStock: 20,
//       description: "A popular pants Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
//     },
//     {
//       name: "Classic Pants",
//       category: "Pants",
//       slug: 'classic-pants',
//       image: "/images/tyres.jpeg",
//       price: 75,
//       brand: "Casely",
//       rating: 4.5,
//       numReviews: 10,
//       countInStock: 20,
//       description: "A popular pants Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
//     },
//   ],
// };
// export default data;

export const states = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara"
]
